### ISSUE TITLE
google_credentials.json

### ISSUE THREAD

**Issue by andy4ward2019** [gboeing/outlook-to-google-calendar#4]
I've mounted the script into a docker container on a synology nas drive. Everything seems to be going well but when I try to run ```python quickstart.py``` it fails when loading the google_credentials.json saying that it does not exist

I re read the docs and couldn't see what shape this needed to be in or what details it needed to hold. 

I might be missing a step here that's obvious but wondered if you could point that out please?

Thanks,

**Comment by gboeing** [comment]
Added clearer instructions to the readme:

> The script connects to the Microsoft API using the O365 package and connects to the Google API using its Python client. Familiarize yourself with their documentation as you may need to enable APIs or create credentials per their instructions before you begin.

and 

> Create Google credentials for this application (see overview section above) and save as credentials/google_credentials.json

See the readme for more details.
